# Generated by Django 5.0.7 on 2024-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_blog_link_blog_venue_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
