# Generated by Django 5.0.7 on 2024-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price_now', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_number', models.CharField(max_length=20)),
            ],
        ),
    ]
