# Generated by Django 5.0.7 on 2024-12-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_post_reply_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
