# Generated by Django 5.0.7 on 2024-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_payment_email_payment_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
