# Generated by Django 5.0.7 on 2024-12-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_payment_reference_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_price',
        ),
    ]
