# Generated by Django 5.0.7 on 2024-12-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_message_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
