# Generated by Django 5.0.7 on 2024-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_amount_payment_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='price_now',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
