# Generated by Django 5.0.7 on 2024-12-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_total_price_payment_amount_payment_price_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price_now',
        ),
    ]
