# Generated by Django 5.0.7 on 2024-12-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
