# Generated by Django 5.0.7 on 2024-12-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_payment_price_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
    ]
