# Generated by Django 5.0.7 on 2024-12-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_message_image_url_message_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
