# Generated by Django 5.0.7 on 2024-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
