# Generated by Django 5.0.7 on 2024-12-02 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
