# Generated by Django 5.0.7 on 2024-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_farmer_delete_farmerregistration_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('name', models.CharField(max_length=20)),
                ('farm_nol', models.CharField(blank=True, max_length=20)),
                ('farm_product', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
