# Generated by Django 5.0.7 on 2024-11-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='products_images/')),
                ('date_time', models.DateField()),
                ('price_before', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('price_now', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
