# Generated by Django 5.0.7 on 2024-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_worker_mode_payment_alter_worker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='account',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
