# Generated by Django 5.0.7 on 2024-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_remove_worker_role_remove_worker_user_worker_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='Id_number',
        ),
        migrations.AlterField(
            model_name='worker',
            name='mode_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='id_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
