# Generated by Django 5.0.7 on 2024-11-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_worker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
