# Generated by Django 5.0.7 on 2024-12-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_worker_id_number_alter_worker_mode_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mode_payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
