# Generated by Django 5.0.7 on 2024-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_worker_salary_worker_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status_salary',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
