# Generated by Django 5.0.7 on 2024-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_rename_id_number_worker_id_number_worker_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
