# Generated by Django 5.0.7 on 2024-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_remove_worker_status_salary_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status_salary',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20),
        ),
    ]
