# Generated by Django 5.0.7 on 2024-12-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('Pending', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=20),
        ),
    ]
