# Generated by Django 5.0.7 on 2024-12-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_worker_email_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
